/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 donuts.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/donuts-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Donut1.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut2.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut3.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut4.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut5.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut6.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut7.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut8.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut9.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut10.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut11.geometry} material={materials.Donut} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
      <mesh geometry={nodes.Donut12.geometry} material={materials.Donut} position={[0.07, 5.4, 0.91]} rotation={[-Math.PI / 2, 0, 2.7]} scale={100} />
    </group>
  )
}

useGLTF.preload('/donuts-transformed.glb')
